"""
jvpm_dict
Method finds bytecode in dictionary and returns opcode
"""
def get_opcode(byte_code):
    jvpm_dict = {
            "91": "i2b", # convert an int into a byte
            "92": "i2c",
            "87": "i2d",
            "86": "i2f",
            "85": "i2l",
            "93": "i2s",
            "60": "iadd",
            "2e": "iaload",
            "7e": "iand",
            "4f": "iastore",
            "02": "iconst_m1",
            "03": "iconst_0",
            "04": "iconst_1",
            "05": "incost_2",
            "06": "inconst_3",
            "07": "inconst_4",
            "08": "iconst_5",
            "6c": "idiv",
            "a5": "if_acmpeq",
            "a6": "if_acmpene",
            "9f": "if_icmpeq",
            "a2": "if_icmpge",
            "a3": "if_icmpgt",
            "a4": "if_icmple",
            "a1": "if_icmplt",
            "a0": "if_icmpne",
            "99": "ifeq",
            "9c": "ifge",
            "9d": "ifgt",
            "9e": "ifle",
            "9b": "iflt",
            "9a": "ifne",
            "c7": "ifnonnull",
            "c6": "ifnull",
            "84": "iinc",
            "15": "iload",
            "1a": "iload_0",
            "1b": "iload_1",
            "1c": "iload_2",
            "1d": "iload_3",
            "fe": "impdep1",
            "ff": "impdep2",
            "68": "imul",
            "74": "ineg",
            "c1": "instanceof",
            "ba": "invokedynamic",
            "b9": "invokeinterface",
            "b7": "invokespecial",
            "b8": "invokestatic",
            "b6": "invokevirtual",
            "80": "ior",
            "70": "irem",
            "ac": "ireturn",
            "78": "ishl",
            "7a": "ishr",
            "36": "istore",
            "3b": "istore_0",
            "3c": "istore_1",
            "3d": "istore_2",
            "3e": "istore_3",
            "64": "isub",
            "7c": "iushr",
            "82": "ixor"
            }
    return jvpm_dict[byte_code]
